### ISSUE TITLE
no screen?

### ISSUE THREAD

**Issue by VoidedGorilla** [ToniMacaroni/ComputerInterface#73]
due to the new update, the computer interface is broken, it goes back to the gtag pc and makes it blank, there is literally no pc screen.
![unknown (2)](https://user-images.githubusercontent.com/103909928/198733624-dd10765c-8760-4e39-83ea-9239af71de22.png)

**Comment by XLIKES1** [comment]
same i have that i learnt how to get in codes with it like that but ye its gone

**Comment by developer9998** [comment]
i have fixed this issue in the newest pull request that will hopefully get used for the next version of the mod. this issue was due to the mesh for the ingame computer have it's location changed around. this has happened a few times already but for different cases such as the paintbrawl update moving the palm location

**Comment by MrMod28** [comment]
how do i connect
to: develp

> i have fixed this issue in the newest pull request that will hopefully get used for the next version of the mod. this issue was due to the mesh for the ingame computer have it's location changed around. this has happened a few times already but for different cases such as the paintbrawl update moving the palm location

how do i install
